services:

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
      MYSQL_DATABASE: wiseSaying
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge